<?php if ($this->pageCount): ?>
    <!-- First page link -->
    <?php if (isset($this->previous)): ?>
        <li>
            <a href="<?php echo $this->url(array('page' => $this->first)); ?>">&laquo;</a>
        </li>
    <?php else: ?>
        <li class="disabled">
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
    <?php endif; ?>

    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?>
            <li>
                <a href="<?php echo $this->url(array('page' => $page)); ?>">
                    <?php echo $page; ?>
                </a>
            </li>
        <?php else: ?>
            <li class="active"><a href="#"><?php echo $page; ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>

    <!-- Last page link -->
    <?php if (isset($this->next)): ?>
        <li>
            <a href="<?php echo $this->url(array('page' => $this->last)); ?>">&raquo;</a>
        </li>
    <?php else: ?>
        <li class="disabled">
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    <?php endif; ?>

    <?php


 endif;