<?php /* @var $this Zend_View*/ ?>
<?php $this->set?>
<html>
    <head>
    </head>
    <body>
        <header>
            <menu>
                <nav></nav>
            </menu>
        </header>
        <article>
            <header>Title</header>
            <section>
                <time></time>
                <?= $this->layout()->content; ?>
            </section>
        </article>
        <aside>
           <?php $this->displayAdvertise(10); //display 10 advertise from database?>     
        </aside>
        <footer>
            <address> address</address>
        </footer>
    </body>
</html>