<?php /* @var $this Zend_View */?>
<html>
    <head>
        <meta NAME="robots" CONTENT="noindex, nofollow">
        <meta charset="utf-8">
        <?=$this->headTitle()?>
    </head>
    <body>
        <header>
            <menu>
                <nav></nav>
            </menu>
        </header>
        <section>
            <?= $this->layout()->content; ?>
        </section>
        <footer>
            <address></address>
        </footer>
    </body>
</html>