<?php /* @var $this Zend_View */ ?>
<html>

<?php echo $this->doctype() ;
        ?>
    <head>
        <meta NAME="robots" CONTENT="noindex, nofollow">
        <meta charset="utf-8">
        <?= $this->headTitle() ?>
        <?= $this->headMeta('ao thoi trang cong so so mot the gioi', 'keyword') ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
    </head>
    <body>
        <header>
            <menu>
                <nav><?= $this->render('_header.phtml'); ?></nav>
            </menu>
        </header>
        <section>
            <?= $this->layout()->content; ?>
        </section>
        <section>
        </section>
        <nav>
            <?=$this->partial('_paginator.phtml')?>
        </nav>
        <footer>
            <?php
            echo $this->partial('_footer.phtml');
            ?>
        </footer>
    </body>
</html>