
<section id="indexManageSupplier">
    <table class="table table-striped ">
        <header><h1 class="h1">Bảng danh sách các nhà cung cấp:</h1></header>
        <thead>
            <tr>
                <th>STT</th>
                <th>Họ và tên</th>
                <th>Địa chỉ</th>
                <th>Facebook</th>
                <th>Số điện thoại</th>
                <th>Email</th>
                <th>Fax</th>
                <th colspan="2">Tác vụ</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $suppliers = $this->suppliers;
            $number = 0;
            foreach ($suppliers as $supplier):
                $number++;
                $supplierName = $this->escape($supplier->SuppName);
                $supplierAddress = $this->escape($supplier->SuppAddress);
                $supplierFacebook = $this->escape($supplier->SuppFacebook);
                $supplierPhone = $this->escape($supplier->SuppPhone);
                $supplierEmail = $this->escape($supplier->SuppEmail);
                $supplierFax = $this->escape($supplier->SuppFax);
                $supplierId = $this->escape($supplier->SuppId);
                $urlDelete = 'manage-supplier/delete/id/' . $supplierId;
                $urlEdit = 'manage-supplier/edit/id/' . $supplierId;
                ?>
                <tr>
                    <td><?= $number ?></td>
                    <td><?= $supplierName ?></td>
                    <td><?= $supplierAddress ?></td>
                    <td><?= $supplierFacebook ?></td>
                    <td><?= $supplierPhone ?></td>
                    <td><?= $supplierEmail ?></td>
                    <td><?= $supplierFax ?></td>
                    <td><a href="<?= $urlDelete ?>">Xóa</a></td>
                    <td><a href="<?= $urlEdit ?>">Sửa</a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>

<?=$this->translate('Danh mục sản phẩm')?>